version: '3'

x-postgres-env: &postgres-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: attendancechecker

services:
  # FastAPI backend service
  backend:
    build: ./backend
    command: >
      bash -c "python setup_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/attendancechecker
      - SECRET_KEY=your_secure_secret_key_here
    networks:
      - app-network

  # Frontend static service
  frontend:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: python -m http.server 8001
    ports:
      - "8001:8001"

  # PostgreSQL service
  postgres:
    image: postgres:14
    environment:
      <<: *postgres-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Streamlit service
  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      <<: *postgres-env

  # Flask service
  flask:
    build: ./flask
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      <<: *postgres-env

  # Django service
  django:
    build: ./django
    ports:
      - "8002:8000"
    depends_on:
      - postgres
    environment:
      <<: *postgres-env

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
