"""create initial schema

Revision ID: 0c90accc5a2f
Revises: 
Create Date: 2025-04-06 22:29:49.465596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c90accc5a2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendance_attendanceid'), 'attendance', ['attendanceid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_attendanceid'), table_name='attendance')
    # ### end Alembic commands ###
